In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])

print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)   
print(a.dtype)
print(b.dtype)

(3,)
(2, 2)
1
2
int64
int64


In [ ]:
print(np.zeros((2,3)))  #zero matrix
print()
print(np.ones(3,))  #1d matrix with ones
print()
print(np.eye(3))  # identity matrix of order 3
print()
print(np.arange(1,10,2))   # 1 to 10 numbers with the gap of 2
print()
print(np.linspace(0,1,5))  #  5 numbers between 0 to 1 (both inclusive)        => formula:  (a,b,n)  -> d = (b-a)/n-1    sequence = a0, a0 + d, a0 + 2d, ...

[[0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1 3 5 7 9]

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# ARRAY MANIPULATION

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[:,1])

#reshape and flatten
print(arr.reshape(3,2))  # it reshapes (changes the order of matrix)
print(arr.flatten())  # it makes it 1d array

2
[2 5]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
